name: offer_show
description: Project for hepan_lite

publish_to: "none"
version: 1.0.13+2

environment:
  sdk: '>=3.0.0 <=3.22.0'

dependencies:
  # webview_all: ^0.4.5
  wechat_camera_picker: ^4.3.1
  flutter_socks_proxy: ^0.0.2
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  # webview_flutter: ^4.0.6
  flutter_keyboard_visibility: ^6.0.0
  route_transitions: ^2.0.1
  screenshot: ^3.0.0
  # flutter_qr_reader: ^1.0.5
  bitsdojo_window: ^0.1.5
  window_manager: ^0.3.9
  images_picker: ^1.2.11
  # flick_video_player: ^0.7.0
  video_player: ^2.4.6
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.1.0
  device_info_plus: ^10.1.2
  sizer: ^2.0.15
  flutter_picker: ^2.0.3
  badges: ^3.1.2
  characters: ^1.2.0
  # flutter_vibrate: ^1.3.0
  # vibration: ^1.7.3
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  photo_view: ^0.15.0
  provider:
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  url_launcher: ^6.0.20
  # heic_to_jpg: ^0.2.0
  # image_gallery_saver: ^2.0.3
  image_gallery_saver_plus: ^3.0.5
  cached_network_image: ^3.3.1
  octo_image: ^2.0.0
  flutter_cache_manager: ^3.3.0
  cached_network_image_platform_interface: ^4.0.0
  cached_network_image_web: ^1.0.0
  crop_your_image: ^1.1.0
  flutter_image_compress: ^2.3.0
  # share_plus: ^6.3.4
  lottie: ^3.1.2
  flutter_bounce: ^1.1.0
  syncfusion_flutter_sliders: ^26.1.40
  sticky_headers: ^0.3.0+2
  adaptive_theme: ^3.0.0
  animate_do: ^3.3.4
  percent_indicator: ^4.2.2
  html: ^0.15.0
  bubble_tab_indicator: ^0.1.6
  pull_to_refresh: ^2.0.0
  flutter_displaymode: ^0.6.0
  path_provider: ^2.0.11
  # wakelock: ^0.6.2
  chewie: ^1.3.4
  # device_info: ^2.0.3
  permission_handler: ^11.3.1
  webview_flutter: ^4.2.0
  dismissible_page: ^1.0.2
  in_app_review: ^2.0.9
  # flutter_markdown: ^0.7.4+1 # 已引入源码
  flutter_math_fork:
    git:
      url: git@github.com:dakshatsuraasa/flutter_math
      ref: bd30a5faca93fe1279f1d39d347f9dbe8472877b
  # flutter_markdown_latex : ^0.3.4 # 已引入源码
  # flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # fonts:
  #   - family: MiSans
  #     fonts:
  #       - asset: lib/font/MiSans-Regular.ttf
  assets:
    # - lib/font/
    - lib/img/celebration/
    - lib/emoji/1/
    - lib/emoji/2/
    - lib/emoji/3/
    - lib/emoji/4/
    - lib/emoji/5/
    - lib/img/
    - lib/img/water_total/
    - lib/img/banner/
    - lib/img/setting/
    - lib/img/square/
    - lib/img/square/column/
    - lib/img/person/
    - lib/img/home/
    - lib/img/msg/
    - lib/img/me/
    - lib/img/me_dark/
    - lib/page/hot/img/
    - lib/collect_btn/
    - lib/page/msg_three/
    - lib/lottie/
    - lib/img/explore/
    - lib/img/topic_dark_func/
  
